# Copyright 2021 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

---
address:
  scratch_reg: 0x40000000
  wakeup_reg: 0x40000004
  tcdm_start: 0x40000008
  tcdm_end: 0x4000000C
  nr_cores: 0x40000010
  uart: 0xC0000000
  # Not supported in MemPool
  barrier_reg:
    start: 0x50000000
    offset: 0x100000
  cluster_base_hartid: 0x50000001
  cluster_num: 0x50000002
  cluster_id: 0x50000003
  cl_clint: 0x40000060
  clint: 0xFFFF0000
memory:
  tcdm:
    start: 0x0
    size: 0x4000000
    offset: 0x4000000
    latency: 7
  dram:
    start: 0x80000000
    size: 0x01000000
    offset: 0x0
    latency: 10
  periphs:
    start: 0x40000000
    size: 0x20000
    offset: 0x0
    latency: 7
    callbacks:
      - name: zero-memory
        size: 0x10000
      - name: mempool-dma
        size: 0x1C
inst_latency:
  mul: 3
  mulh: 3
  mulhsu: 3
  mulhu: 3
  div: 3
  divu: 3
  rem: 3
  remu: 3
  fmulex.s.h: 3
  fmacex.s.h: 3
  fmulex.s.b: 3
  fmacex.s.b: 3
  fadd.s: 3
  fsub.s: 3
  fmul.s: 3
  fdiv.s: 3
  fadd.q: 3
  fsub.q: 3
  fmul.q: 3
  fdiv.q: 3
  fadd.h: 3
  fsub.h: 3
  fmul.h: 3
  fdiv.h: 3
  vfadd.s: 3
  vfadd.r.s: 3
  vfsub.s: 3
  vfsub.r.s: 3
  vfmul.s: 3
  vfmul.r.s: 3
  vfdiv.s: 3
  vfdiv.r.s: 3
  vfmin.s: 3
  vfmin.r.s: 3
  vfmax.s: 3
  vfmax.r.s: 3
  vfmac.s: 3
  vfmac.r.s: 3
  vfmre.s: 3
  vfmre.r.s: 3
  vfsgnj.s: 3
  vfsgnj.r.s: 3
  vfsgnjn.s: 3
  vfsgnjn.r.s: 3
  vfsgnjx.s: 3
  vfsgnjx.r.s: 3
  vfeq.s: 3
  vfeq.r.s: 3
  vfne.s: 3
  vfne.r.s: 3
  vflt.s: 3
  vflt.r.s: 3
  vfge.s: 3
  vfge.r.s: 3
  vfle.s: 3
  vfle.r.s: 3
  vfgt.s: 3
  vfgt.r.s: 3
  vfadd.h: 3
  vfadd.r.h: 3
  vfsub.h: 3
  vfsub.r.h: 3
  vfmul.h: 3
  vfmul.r.h: 3
  vfdiv.h: 3
  vfdiv.r.h: 3
  vfmin.h: 3
  vfmin.r.h: 3
  vfmax.h: 3
  vfmax.r.h: 3
  vfmac.h: 3
  vfmac.r.h: 3
  vfmre.h: 3
  vfmre.r.h: 3
  vfsgnj.h: 3
  vfsgnj.r.h: 3
  vfsgnjn.h: 3
  vfsgnjn.r.h: 3
  vfsgnjx.h: 3
  vfsgnjx.r.h: 3
  vfeq.h: 3
  vfeq.r.h: 3
  vfne.h: 3
  vfne.r.h: 3
  vflt.h: 3
  vflt.r.h: 3
  vfge.h: 3
  vfge.r.h: 3
  vfle.h: 3
  vfle.r.h: 3
  vfgt.h: 3
  vfgt.r.h: 3
  vfcpka.h.s: 3
  vfcpkb.h.s: 3
  vfadd.b: 3
  vfadd.r.b: 3
  vfsub.b: 3
  vfsub.r.b: 3
  vfmul.b: 3
  vfmul.r.b: 3
  vfdiv.b: 3
  vfdiv.r.b: 3
  vfmin.b: 3
  vfmin.r.b: 3
  vfmax.b: 3
  vfmax.r.b: 3
  vfmac.b: 3
  vfmac.r.b: 3
  vfmre.b: 3
  vfmre.r.b: 3
  vfsgnj.b: 3
  vfsgnj.r.b: 3
  vfsgnjn.b: 3
  vfsgnjn.r.b: 3
  vfsgnjx.b: 3
  vfsgnjx.r.b: 3
  vfeq.b: 3
  vfeq.r.b: 3
  vfne.b: 3
  vfne.r.b: 3
  vflt.b: 3
  vflt.r.b: 3
  vfge.b: 3
  vfge.r.b: 3
  vfle.b: 3
  vfle.r.b: 3
  vfgt.b: 3
  vfgt.r.b: 3
  vfcpka.b.s: 3
  vfcpkb.b.s: 3
  vfcpkc.b.s: 3
  vfcpkd.b.s: 3
  vfdotpex.s.h: 3
  vfndotpex.s.h: 3
  vfdotpex.h.b: 3
  vfndotpex.h.b: 3
  fcdotpex.s.h: 3
  fcndotpex.s.h: 3
  fccdotpex.s.h: 3
  fccndotpex.s.h: 3
  vfdotpex.s.r.h: 3
  vfndotpex.s.r.h: 3
  vfdotpex.s.r.h: 3
  vfndotpex.s.r.h: 3
  pv.add.sci.h: 2
  pv.add.sci.b: 2
  pv.sub.sci.h: 2
  pv.sub.sci.b: 2
  pv.avg.sci.h: 2
  pv.avg.sci.b: 2
  pv.avgu.sci.h: 2
  pv.avgu.sci.b: 2
  pv.min.sci.h: 2
  pv.min.sci.b: 2
  pv.minu.sci.h: 2
  pv.minu.sci.b: 2
  pv.max.sci.h: 2
  pv.max.sci.b: 2
  pv.maxu.sci.h: 2
  pv.maxu.sci.b: 2
  pv.srl.sci.h: 2
  pv.srl.sci.b: 2
  pv.sra.sci.h: 2
  pv.sra.sci.b: 2
  pv.sll.sci.h: 2
  pv.sll.sci.b: 2
  pv.or.sci.h: 2
  pv.or.sci.b: 2
  pv.xor.sci.h: 2
  pv.xor.sci.b: 2
  pv.and.sci.h: 2
  pv.and.sci.b: 2
  pv.extract.h: 2
  pv.extract.b: 2
  pv.extractu.h: 2
  pv.extractu.b: 2
  pv.insert.h: 2
  pv.insert.b: 2
  pv.dotsp.sci.h: 2
  pv.dotsp.sci.b: 2
  pv.dotup.sci.h: 2
  pv.dotup.sci.b: 2
  pv.dotusp.sci.h: 2
  pv.dotusp.sci.b: 2
  pv.sdotsp.sci.h: 2
  pv.sdotsp.sci.b: 2
  pv.sdotup.sci.h: 2
  pv.sdotup.sci.b: 2
  pv.sdotusp.sci.h: 2
  pv.sdotusp.sci.b: 2
  pv.cmpeq.sci.h: 2
  pv.cmpeq.sci.b: 2
  pv.cmpne.sci.h: 2
  pv.cmpne.sci.b: 2
  pv.cmpgt.sci.h: 2
  pv.cmpgt.sci.b: 2
  pv.cmpge.sci.h: 2
  pv.cmpge.sci.b: 2
  pv.cmplt.sci.h: 2
  pv.cmplt.sci.b: 2
  pv.cmple.sci.h: 2
  pv.cmple.sci.b: 2
  pv.cmpgtu.sci.h: 2
  pv.cmpgtu.sci.b: 2
  pv.cmpgeu.sci.h: 2
  pv.cmpgeu.sci.b: 2
  pv.cmpltu.sci.h: 2
  pv.cmpltu.sci.b: 2
  pv.cmpleu.sci.h: 2
  pv.cmpleu.sci.b: 2
  pv.shuffle.sci.h: 2
  pv.shufflei0.sci.b: 2
  pv.shufflei1.sci.b: 2
  pv.shufflei2.sci.b: 2
  pv.shufflei3.sci.b: 2
  p.extractr: 2
  p.extractur: 2
  p.insertr: 2
  p.bsetr: 2
  p.bclrr: 2
  p.cnt: 2
  p.clipr: 2
  p.clipur: 2
  p.mac: 2
  p.msu: 2
  p.min: 2
  p.minu: 2
  p.max: 2
  p.maxu: 2
  p.lb.rrpost: 2
  p.lbu.rrpost: 2
  p.lh.rrpost: 2
  p.lhu.rrpost: 2
  p.lw.rrpost: 2
  p.lb.rr: 2
  p.lbu.rr: 2
  p.lh.rr: 2
  p.lhu.rr: 2
  p.lw.rr: 2
  p.slet: 2
  p.sletu: 2
  pv.add.h: 2
  pv.add.sc.h: 2
  pv.add.b: 2
  pv.add.sc.b: 2
  pv.sub.h: 2
  pv.sub.sc.h: 2
  pv.sub.b: 2
  pv.sub.sc.b: 2
  pv.avg.h: 2
  pv.avg.sc.h: 2
  pv.avg.b: 2
  pv.avg.sc.b: 2
  pv.avgu.h: 2
  pv.avgu.sc.h: 2
  pv.avgu.b: 2
  pv.avgu.sc.b: 2
  pv.min.h: 2
  pv.min.sc.h: 2
  pv.min.b: 2
  pv.min.sc.b: 2
  pv.minu.h: 2
  pv.minu.sc.h: 2
  pv.minu.b: 2
  pv.minu.sc.b: 2
  pv.max.h: 2
  pv.max.sc.h: 2
  pv.max.b: 2
  pv.max.sc.b: 2
  pv.maxu.h: 2
  pv.maxu.sc.h: 2
  pv.maxu.b: 2
  pv.maxu.sc.b: 2
  pv.srl.h: 2
  pv.srl.sc.h: 2
  pv.srl.b: 2
  pv.srl.sc.b: 2
  pv.sra.h: 2
  pv.sra.sc.h: 2
  pv.sra.b: 2
  pv.sra.sc.b: 2
  pv.sll.h: 2
  pv.sll.sc.h: 2
  pv.sll.b: 2
  pv.sll.sc.b: 2
  pv.or.h: 2
  pv.or.sc.h: 2
  pv.or.b: 2
  pv.or.sc.b: 2
  pv.xor.h: 2
  pv.xor.sc.h: 2
  pv.xor.b: 2
  pv.xor.sc.b: 2
  pv.and.h: 2
  pv.and.sc.h: 2
  pv.and.b: 2
  pv.and.sc.b: 2
  pv.dotsp.h: 2
  pv.dotsp.sc.h: 2
  pv.dotsp.b: 2
  pv.dotsp.sc.b: 2
  pv.dotup.h: 2
  pv.dotup.sc.h: 2
  pv.dotup.b: 2
  pv.dotup.sc.b: 2
  pv.dotusp.h: 2
  pv.dotusp.sc.h: 2
  pv.dotusp.b: 2
  pv.dotusp.sc.b: 2
  pv.sdotsp.h: 2
  pv.sdotsp.sc.h: 2
  pv.sdotsp.b: 2
  pv.sdotsp.sc.b: 2
  pv.sdotup.h: 2
  pv.sdotup.sc.h: 2
  pv.sdotup.b: 2
  pv.sdotup.sc.b: 2
  pv.sdotusp.h: 2
  pv.sdotusp.sc.h: 2
  pv.sdotusp.b: 2
  pv.sdotusp.sc.b: 2
  pv.cmpeq.h: 2
  pv.cmpeq.sc.h: 2
  pv.cmpeq.b: 2
  pv.cmpeq.sc.b: 2
  pv.cmpne.h: 2
  pv.cmpne.sc.h: 2
  pv.cmpne.b: 2
  pv.cmpne.sc.b: 2
  pv.cmpgt.h: 2
  pv.cmpgt.sc.h: 2
  pv.cmpgt.b: 2
  pv.cmpgt.sc.b: 2
  pv.cmpge.h: 2
  pv.cmpge.sc.h: 2
  pv.cmpge.b: 2
  pv.cmpge.sc.b: 2
  pv.cmplt.h: 2
  pv.cmplt.sc.h: 2
  pv.cmplt.b: 2
  pv.cmplt.sc.b: 2
  pv.cmple.h: 2
  pv.cmple.sc.h: 2
  pv.cmple.b: 2
  pv.cmple.sc.b: 2
  pv.cmpgtu.h: 2
  pv.cmpgtu.sc.h: 2
  pv.cmpgtu.b: 2
  pv.cmpgtu.sc.b: 2
  pv.cmpgeu.h: 2
  pv.cmpgeu.sc.h: 2
  pv.cmpgeu.b: 2
  pv.cmpgeu.sc.b: 2
  pv.cmpltu.h: 2
  pv.cmpltu.sc.h: 2
  pv.cmpltu.b: 2
  pv.cmpltu.sc.b: 2
  pv.cmpleu.h: 2
  pv.cmpleu.sc.h: 2
  pv.cmpleu.b: 2
  pv.cmpleu.sc.b: 2
  pv.add.h.div2: 2
  pv.add.h.div4: 2
  pv.add.h.div8: 2
  pv.sub.h.div2: 2
  pv.sub.h.div4: 2
  pv.sub.h.div8: 2
  pv.shuffle.h: 2
  pv.shuffle.b: 2
  pv.shuffle2.h: 2
  pv.shuffle2.b: 2
  pv.pack: 2
  pv.pack.h: 2
  pv.packhi.b: 2
  pv.packlo.b: 2
ssr:
  num_dm: 3
